---
# $ fly -t target sp -p concourse-utils -c concourse.yml -l ~/sec/credentials-test.yml
resources:
- name: src-git
  type: git
  source:
    uri: https://github.com/wdstar/concourse-utils
    #uri: https://gitlab.io.example.com/concourse/utils.git
    skip_ssl_verification: true
    branch: master
  #check_every: 1h  # default: 1m
- name: alpine
  type: docker-image
  source:
    repository: alpine
    tag: 3.6
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
  check_every: 12h  # default: 1m
- name: buildroot
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: base
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
  check_every: 12h  # default: 1m
- name: centos
  type: docker-image
  source:
    repository: centos
    tag: 7
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
  check_every: 12h  # default: 1m
- name: debian
  type: docker-image
  source:
    repository: debian
    tag: stable-slim
    #tag: 9
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
  check_every: 12h  # default: 1m
- name: ubuntu
  type: docker-image
  source:
    repository: ubuntu
    tag: latest
    registry_mirror: https://((registry-mirror-domain))
    ca_certs:
    - domain: ((registry-mirror-domain))
      cert: ((docker-reg-ca-cert))
  check_every: 12h  # default: 1m

jobs:
- name: install-ca-certs-tests
  plan:
  - get: src-git
    params:
      depth: 5
  - aggregate:
    - do:
      - get: alpine
      - task: alpine-test
        image: alpine
        params:
          CA_CERTS: ((ca-certs))
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            #path: src-git/install-ca-certs/alpine.sh
            path: /bin/sh
            args:
            - -c
            - |
              src-git/install-ca-certs/alpine.sh
              tail /etc/ssl/certs/ca-certificates.crt
    - do:
      - get: buildroot
      - task: buildroot-test
        image: buildroot
        params:
          CA_CERTS: ((ca-certs))
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            #path: src-git/install-ca-certs/buildroot.sh
            path: /bin/sh
            args:
            - -c
            - |
              src-git/install-ca-certs/buildroot.sh
              tail /etc/ssl/certs/ca-certificates.crt
    - do:
      - get: centos
      - task: centos-test
        image: centos
        params:
          CA_CERTS: ((ca-certs))
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            #path: src-git/install-ca-certs/centos.sh
            path: /bin/sh
            args:
            - -c
            - |
              src-git/install-ca-certs/centos.sh
              tail /etc/pki/tls/certs/ca-bundle.crt
    - do:
      - get: debian
      - task: debian-test
        image: debian
        params:
          CA_CERTS: ((ca-certs))
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            #path: src-git/install-ca-certs/debian.sh
            path: /bin/sh
            args:
            - -c
            - |
              src-git/install-ca-certs/debian.sh
              tail /etc/ssl/certs/ca-certificates.crt
    - do:
      - get: ubuntu
      - task: ubuntu-test
        image: ubuntu
        params:
          CA_CERTS: ((ca-certs))
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            #path: src-git/install-ca-certs/debian.sh
            path: /bin/sh
            args:
            - -c
            - |
              src-git/install-ca-certs/debian.sh
              tail /etc/ssl/certs/ca-certificates.crt
- name: update-system-tests
  plan:
  - get: src-git
    params:
      depth: 5
  - aggregate:
    - do:
      - get: alpine
      - task: alpine-test
        image: alpine
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            path: src-git/update-system/alpine.sh
    - do:
      - get: centos
      - task: centos-test
        image: centos
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            path: src-git/update-system/centos.sh
    - do:
      - get: debian
      - task: debian-test
        image: debian
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            path: src-git/update-system/debian.sh
    - do:
      - get: ubuntu
      - task: ubuntu-test
        image: ubuntu
        config:
          platform: linux
          inputs:
          - name: src-git
          run:
            path: src-git/update-system/debian.sh
